# Generated by Django 4.2.7 on 2023-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_remove_brandmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
