# Generated by Django 4.2.7 on 2023-12-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='brand_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
