# Generated by Django 4.2.7 on 2023-12-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_carmodel_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
    ]
