# Generated by Django 4.2.7 on 2023-12-27 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0004_carmodel_is_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='is_buy',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='purchased',
            field=models.ManyToManyField(blank=True, related_name='purchased_car', to=settings.AUTH_USER_MODEL),
        ),
    ]
